language: python
python:
  - "2.7"
addons:
  apt:
    sources:
    packages:
      - blender
install:
  # Copy the blendmocap addon into the default addons directory for blender
  - sudo mkdir -p /usr/share/blender/scripts/addons
  - sudo cp blendmocap.py /usr/share/blender/scripts/addons/blendmocap.py
script:
  - python tests.py
