language: python
python:
  - "2.7"
addons:
  apt:
    sources:
    packages:
      - blender
install:
  # Copy the blendmocap addon into the default addons directory for blender
  - cp blendmocap.py ~/.config/blender/2.76/scripts/addons/blendmocap.py
script:
  - python tests.py
